---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.12'

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

      - name: Lint Helm Chart
        run: helm lint chart

      - name: Test Go
        run: make test

      - name: Build image
        run: make build-docker

      - name: Build Helm Chart
        run: helm package chart

