---
name: Publish helm chart
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          mkdir owm-exporter
          cp -Rv chart/* owm-exporter/

      - name: Push to chart repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_PUSH }}
        with:
          source-directory: owm-exporter/
          destination-github-username: rkosegi
          destination-repository-name: helm-charts
          target-directory: charts/owm-exporter
          user-email: richard.kosegi@gmail.com
          commit-message: "chart: owm-exporter@$GITHUB_REF"
          target-branch: main
